# percentage of data to use
percentage: 100

# model version
tau: 3
# gpu device id
gpu: 0

# output folder
output: 'models/mycmds_tau3'
# use fine_tuning version
fine_tune: False
# can be omitted if fine_tune is False
fine_tune_epochs: 0

# model parameters
epochs: 500
init_lr: 0.1
lr_lower_limit: 0
warmup_epoch: 5
batch_size: 100
# optimizer parameters
weight_decay: 0.001
momentum: 0.9

seed: 42
